name: Package Slow Loris Attack

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore --self-contained true --output dist
      
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
